table 'Dim Promotion'
	lineageTag: ba922d0b-9bce-4085-b55b-14b6e9ba31f7

	measure 'Sum Dim' = SUM('Fact Table'[Net Sale])
		lineageTag: 5c4dce3e-d499-4f38-9949-d6d59ef4f285

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PromotionID
		dataType: string
		lineageTag: ab828e49-b9a8-434d-add3-41e45849a29f
		summarizeBy: none
		sourceColumn: PromotionID

		annotation SummarizationSetBy = Automatic

	column 'Promotion Name'
		dataType: string
		lineageTag: 7bb32540-31de-4f11-9e63-af8c7d39db97
		summarizeBy: none
		sourceColumn: Promotion Name

		annotation SummarizationSetBy = Automatic

	column 'Ad Type'
		dataType: string
		lineageTag: b79f003b-5ed2-4f50-a0e6-8ab4fa77eb95
		summarizeBy: none
		sourceColumn: Ad Type

		annotation SummarizationSetBy = Automatic

	column 'Coupon Code'
		dataType: string
		lineageTag: 0eec664b-6c64-4f3f-ab76-18de47fc2687
		summarizeBy: none
		sourceColumn: Coupon Code

		annotation SummarizationSetBy = Automatic

	column 'Price Reduction Type'
		dataType: string
		lineageTag: 5346c6c3-fd42-436d-9836-c641b5b00315
		summarizeBy: none
		sourceColumn: Price Reduction Type

		annotation SummarizationSetBy = Automatic

	column Percentage
		dataType: string
		lineageTag: ead28269-0e2a-46ac-a51c-a41b52b77d61
		summarizeBy: none
		sourceColumn: Percentage

		annotation SummarizationSetBy = Automatic

	partition 'Dim Promotion' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Dell\Downloads\Udemy - Complete Data Analyst Bootcamp From Basics To Advanced 2024-10\23 - Power BI Project 1, Sales Data Analysis\2 -Store Data.xlsx"), null, true),
				    #"Dim Promotion _Sheet" = Source{[Item="Dim Promotion ",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(#"Dim Promotion _Sheet",{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"PromotionID", type text}, {"Promotion Name", type text}, {"Ad Type", type text}, {"Coupon Code", type text}, {"Price Reduction Type", type text}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type1", "Percentage", each if [PromotionID] = "PR001" then 20 else if [PromotionID] = "PR002" then 10 else if [PromotionID] = "PR003" then 50 else if [PromotionID] = "PR004" then 50 else 70)
				in
				    #"Added Conditional Column"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

