table 'Fact Table'
	lineageTag: 04aca74f-3121-4f39-aea1-238b6d2d4141

	measure 'Total Orders' = COUNT('Fact Table'[Order ID])
		formatString: 0
		lineageTag: 2c8aee84-0949-400f-83a6-0c9d49211610

	column 'Date (dd/mm/yyyy)'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a5c3a5e5-bf23-405b-ba3d-aabccd470529
		summarizeBy: none
		sourceColumn: Date (dd/mm/yyyy)

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CustomerID
		dataType: string
		lineageTag: badd1c14-82b8-4cae-8d41-30341bab656c
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column PromotionID
		dataType: string
		lineageTag: 0d6cf076-51ca-4400-a84e-9b6e862f7903
		summarizeBy: none
		sourceColumn: PromotionID

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 93e70a01-01c6-4213-bf5f-308cb67c93d4
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column 'Units Sold'
		dataType: int64
		formatString: 0
		lineageTag: cae3cacf-9b27-44d3-8503-fd038a34ed8d
		summarizeBy: sum
		sourceColumn: Units Sold

		annotation SummarizationSetBy = Automatic

	column 'Price per unit'
		dataType: int64
		formatString: 0
		lineageTag: 9343aec9-e840-4958-959f-9047dc7147f1
		summarizeBy: sum
		sourceColumn: Price per unit

		annotation SummarizationSetBy = Automatic

	column TotalSales
		dataType: int64
		formatString: 0
		lineageTag: 04dc5c76-e803-4616-bba0-97304288a5eb
		summarizeBy: sum
		sourceColumn: TotalSales

		annotation SummarizationSetBy = Automatic

	column 'Percentage Discount'
		dataType: int64
		formatString: 0
		lineageTag: 6244e4a7-dc74-493a-b138-c33619b722e9
		summarizeBy: sum
		sourceColumn: Percentage Discount

		annotation SummarizationSetBy = Automatic

	column 'Discount Value'
		dataType: double
		lineageTag: c052acff-d0b2-4f31-a3b8-e753b18a49a4
		summarizeBy: sum
		sourceColumn: Discount Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Net Sale'
		dataType: double
		lineageTag: a04c1dd5-34e8-41d8-b0fb-548e7463f33b
		summarizeBy: sum
		sourceColumn: Net Sale

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 259b20db-df37-43ff-bc66-b52f4f78c49c
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Order ID'
		dataType: string
		lineageTag: a66fd0a4-430e-4b92-93db-a0d40ac1f729
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	partition 'Fact Table' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Dell\Downloads\Udemy - Complete Data Analyst Bootcamp From Basics To Advanced 2024-10\23 - Power BI Project 1, Sales Data Analysis\2 -Store Data.xlsx"), null, true),
				    Sheet3_Sheet = Source{[Item="Sheet3",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet3_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date (dd/mm/yyyy)", type date}, {"CustomerID", type text}, {"PromotionID", type any}, {"Product ID", type text}, {"Units Sold", Int64.Type}, {"Price Per Unit", type any}, {"Total Sales", type any}, {"Discount Percentage", type any}, {"Discount Value", type any}, {"Net Sales", type any}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"Product ID"}, #"Dim Product", {"ProductID"}, "Dim Product", JoinKind.LeftOuter),
				    #"Expanded Dim Product" = Table.ExpandTableColumn(#"Merged Queries", "Dim Product", {"Price (INR)"}, {"Dim Product.Price (INR)"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded Dim Product",{"Price Per Unit"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Dim Product.Price (INR)", "Price per unit"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"Date (dd/mm/yyyy)", "CustomerID", "PromotionID", "Product ID", "Price per unit", "Units Sold", "Total Sales", "Discount Percentage", "Discount Value", "Net Sales"}),
				    #"Added Custom" = Table.AddColumn(#"Reordered Columns", "CustomTotalSales", each [Price per unit]*[Units Sold]),
				    #"Removed Columns1" = Table.RemoveColumns(#"Added Custom",{"Total Sales"}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Removed Columns1",{"Date (dd/mm/yyyy)", "CustomerID", "PromotionID", "Product ID", "Price per unit", "Units Sold", "CustomTotalSales", "Discount Percentage", "Discount Value", "Net Sales"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Reordered Columns1",{{"CustomTotalSales", "TotalSales"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns1",{{"TotalSales", Int64.Type}}),
				    #"Merged Queries1" = Table.NestedJoin(#"Changed Type1", {"PromotionID"}, #"Dim Promotion", {"PromotionID"}, "Dim Promotion", JoinKind.LeftOuter),
				    #"Expanded Dim Promotion" = Table.ExpandTableColumn(#"Merged Queries1", "Dim Promotion", {"Percentage"}, {"Dim Promotion.Percentage"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Expanded Dim Promotion",null,0,Replacer.ReplaceValue,{"Dim Promotion.Percentage"}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Replaced Value",{"Discount Percentage"}),
				    #"Reordered Columns2" = Table.ReorderColumns(#"Removed Columns2",{"Date (dd/mm/yyyy)", "CustomerID", "PromotionID", "Product ID", "Price per unit", "Units Sold", "TotalSales", "Dim Promotion.Percentage", "Discount Value", "Net Sales"}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Reordered Columns2",{{"Dim Promotion.Percentage", "Percentage Discount"}}),
				    #"Added Custom1" = Table.AddColumn(#"Renamed Columns2", "DiscountValue", each [Price per unit]*[Discount Value]),
				    #"Removed Columns3" = Table.RemoveColumns(#"Added Custom1",{"DiscountValue"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Removed Columns3",{{"Percentage Discount", Int64.Type}}),
				    #"Added Custom2" = Table.AddColumn(#"Changed Type2", "Discount Value.1", each [Price per unit]*[Discount Value]),
				    #"Removed Columns4" = Table.RemoveColumns(#"Added Custom2",{"Discount Value.1"}),
				    #"Added Custom3" = Table.AddColumn(#"Removed Columns4", "Discount Value.1", each [Price per unit]*[Percentage Discount]),
				    #"Removed Columns5" = Table.RemoveColumns(#"Added Custom3",{"Discount Value.1"}),
				    #"Added Custom4" = Table.AddColumn(#"Removed Columns5", "Discount Value.1", each (100-[Percentage Discount])*[Price per unit]),
				    #"Removed Columns6" = Table.RemoveColumns(#"Added Custom4",{"Discount Value.1"}),
				    #"Added Custom5" = Table.AddColumn(#"Removed Columns6", "Discount Value.1", each [Price per unit]*([Percentage Discount]/100)),
				    #"Removed Columns7" = Table.RemoveColumns(#"Added Custom5",{"Discount Value"}),
				    #"Renamed Columns3" = Table.RenameColumns(#"Removed Columns7",{{"Discount Value.1", "Discount Value"}}),
				    #"Reordered Columns3" = Table.ReorderColumns(#"Renamed Columns3",{"Date (dd/mm/yyyy)", "CustomerID", "PromotionID", "Product ID", "Price per unit", "Units Sold", "TotalSales", "Percentage Discount", "Discount Value", "Net Sales"}),
				    #"Added Custom6" = Table.AddColumn(#"Reordered Columns3", "Net Sale1", each [TotalSales]-[Discount Value]),
				    #"Added Custom7" = Table.AddColumn(#"Added Custom6", "DiscountValue", each ([TotalSales]*[Percentage Discount])/100),
				    #"Removed Columns8" = Table.RemoveColumns(#"Added Custom7",{"Discount Value"}),
				    #"Reordered Columns4" = Table.ReorderColumns(#"Removed Columns8",{"Date (dd/mm/yyyy)", "CustomerID", "PromotionID", "Product ID", "Price per unit", "Units Sold", "TotalSales", "Percentage Discount", "DiscountValue", "Net Sales", "Net Sale1"}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Reordered Columns4",{{"Net Sale1", type number}, {"DiscountValue", type number}}),
				    #"Removed Columns9" = Table.RemoveColumns(#"Changed Type3",{"Net Sales"}),
				    #"Renamed Columns4" = Table.RenameColumns(#"Removed Columns9",{{"Net Sale1", "Net Sale"}, {"DiscountValue", "Discount Value"}}),
				    #"Added Custom8" = Table.AddColumn(#"Renamed Columns4", "Profit", each 0.1*[Net Sale]),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Added Custom8",{{"Profit", type number}}),
				    #"Added Index" = Table.AddIndexColumn(#"Changed Type4", "Index", 1, 1, Int64.Type),
				    #"Added Index1" = Table.AddIndexColumn(#"Added Index", "Index.1", 1, 1, Int64.Type),
				    #"Removed Columns10" = Table.RemoveColumns(#"Added Index1",{"Index.1"}),
				    #"Reordered Columns5" = Table.ReorderColumns(#"Removed Columns10",{"Index", "Date (dd/mm/yyyy)", "CustomerID", "PromotionID", "Product ID", "Price per unit", "Units Sold", "TotalSales", "Percentage Discount", "Discount Value", "Net Sale", "Profit"}),
				    #"Renamed Columns5" = Table.RenameColumns(#"Reordered Columns5",{{"Index", "Order ID"}}),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Renamed Columns5",{{"Order ID", type text}})
				in
				    #"Changed Type5"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

